name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
        image: kirschbaumdevelopment/laravel-test-runner:8.3
    services:
        postgres:
            image: postgres
            env:
                POSTGRES_USER:  postgres
                POSTGRES_PASSWORD:  docker
                POSTGRES_DB:  challengeribge
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:   
      - uses: actions/checkout@v3
        with:
            fetch-depth: 1
      - name: Config Env
        run:  cp .env.example .env

      - name: Install Composer
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Migrate
        run: |
          php artisan key:generate
          php artisan migrate

     
