name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
        image: kirschbaumdevelopment/laravel-test-runner:8.3
    services:
        postgres:
            image: postgres
    steps:   
      - uses: actions/checkout@v3
        with:
            fetch-depth: 1
      - name: Building Laravel
        run: |
          cp .env.example .env
          composer install --no-progress --prefer-dist --optimize-autoloader
          php artisan key:generate
          php artisan migrate

     
